# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpc_image2_pb2 as grpc__image2__pb2

GRPC_GENERATED_VERSION = '1.64.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_image2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class EnvioDeMensagensStub(object):
    """Define o serviço de envio da mensagem do cliente para o servidor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarMensagem = channel.unary_unary(
                '/sca_ufc.EnvioDeMensagens/EnviarMensagem',
                request_serializer=grpc__image2__pb2.ClienteParaServidor.SerializeToString,
                response_deserializer=grpc__image2__pb2.ServidorParaCliente.FromString,
                _registered_method=True)


class EnvioDeMensagensServicer(object):
    """Define o serviço de envio da mensagem do cliente para o servidor
    """

    def EnviarMensagem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvioDeMensagensServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarMensagem': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarMensagem,
                    request_deserializer=grpc__image2__pb2.ClienteParaServidor.FromString,
                    response_serializer=grpc__image2__pb2.ServidorParaCliente.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sca_ufc.EnvioDeMensagens', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sca_ufc.EnvioDeMensagens', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EnvioDeMensagens(object):
    """Define o serviço de envio da mensagem do cliente para o servidor
    """

    @staticmethod
    def EnviarMensagem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sca_ufc.EnvioDeMensagens/EnviarMensagem',
            grpc__image2__pb2.ClienteParaServidor.SerializeToString,
            grpc__image2__pb2.ServidorParaCliente.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
