# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_image2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_image2.proto\x12\x07sca_ufc\"\x98\x01\n\x13\x43lienteParaServidor\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08id_turma\x18\x02 \x01(\t\x12\x15\n\rid_disciplina\x18\x03 \x01(\t\x12\x10\n\x08id_aluno\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\x02\x12\r\n\x05image\x18\x06 \x01(\x0c\x12\r\n\x05shape\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\x08 \x01(\t\"\xb2\x01\n\x13ServidorParaCliente\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x10\n\x08id_turma\x18\x02 \x01(\t\x12\x15\n\rid_disciplina\x18\x03 \x01(\t\x12\x10\n\x08id_aluno\x18\x04 \x01(\t\x12\x0c\n\x04time\x18\x05 \x01(\x02\x12\r\n\x05image\x18\x06 \x01(\x0c\x12\x0c\n\x04name\x18\x07 \x01(\t\x12\x12\n\nnum_faltas\x18\x08 \x01(\x05\x12\x13\n\x0brepositorio\x18\t \x01(\x0c\x32`\n\x10\x45nvioDeMensagens\x12L\n\x0e\x45nviarMensagem\x12\x1c.sca_ufc.ClienteParaServidor\x1a\x1c.sca_ufc.ServidorParaClienteb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_image2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTEPARASERVIDOR._serialized_start=31
  _CLIENTEPARASERVIDOR._serialized_end=183
  _SERVIDORPARACLIENTE._serialized_start=186
  _SERVIDORPARACLIENTE._serialized_end=364
  _ENVIODEMENSAGENS._serialized_start=366
  _ENVIODEMENSAGENS._serialized_end=462
# @@protoc_insertion_point(module_scope)
